export enum ActionTypes {
  STORE_CREATED = 'STORE_CREATED',
  STORE_UPDATED = 'STORE_UPDATED',
  STORE_DELETED = 'STORE_DELETED',

  ITEM_CREATED = 'ITEM_CREATED',
  ITEM_UPDATED = 'ITEM_UPDATED',
  ITEM_DELETED = 'ITEM_DELETED',
  ITEM_NOTE_CREATED = 'ITEM_NOTE_CREATED',
  ITEM_NOTE_UPDATED = 'ITEM_NOTE_UPDATED',
  ITEM_NOTE_DELETED = 'ITEM_NOTE_DELETED',

  TAG_CREATED = 'TAG_CREATED',
  TAG_UPDATED = 'TAG_UPDATED',
  TAG_DELETED = 'TAG_DELETED',

  USER_REGISTERED = 'USER_REGISTERED',
  USER_UPDATED_HIS_ACCOUNT = 'USER_UPDATED_HIS_ACCOUNT',
  USER_UPDATED_HIS_PASSWORD = 'USER_UPDATED_HIS_PASSWORD',
  USER_CREATED = 'USER_CREATED',
  USER_ACCOUNT_UPDATED = 'USER_ACCOUNT_UPDATED',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
  USER_DELETED = 'USER_DELETED',
}
